name: Backend CI

on:
  push:
    branches: [ main ]
  pull_request:
    # run CI for pull requests on any branch
    branches: ['**']
  workflow_dispatch: {}

jobs:
  test:
    name: Install, Lint & Test (backend)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: ./backend

      - name: Run linter
        run: npm run lint
        working-directory: ./backend
        continue-on-error: true

      - name: Run tests
        run: npm test
        working-directory: ./backend

      - name: Build (if present)
        run: npm run build
        working-directory: ./backend
        continue-on-error: true

  # NOTE: Deployment should be handled by Render provider integrations (connect repo in Render dashboard).

