name: Deploy Trigger

# This workflow listens for successful CI runs and optionally triggers a deployment webhook
# Configure the target webhook in repository secrets: RENDER_DEPLOY_WEBHOOK

on:
  workflow_run:
    workflows: ["Backend CI", "Frontend CI"]
    types:
      - completed

jobs:
  trigger:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Notify about successful CI
        run: |
          echo "Workflow '${{ github.event.workflow_run.name }}' completed successfully."

      - name: Deploy webhook (manual setup required)
        run: |
          echo "No deploy webhook configured. To enable automatic deploys set the repository secret 'RENDER_DEPLOY_WEBHOOK' to your provider webhook URL."
          echo "Example (commented):"
          echo "# curl -X POST -H 'Content-Type: application/json' -d '{\"ref\":\"${{ github.ref }}\",\"sha\":\"${{ github.sha }}\"}' \"$RENDER_DEPLOY_WEBHOOK\""

      # To enable automatic deploys uncomment the following step and add the secret 'RENDER_DEPLOY_WEBHOOK' to repository secrets.
      # - name: Trigger Render/Railway deploy webhook
      #   run: |
      #     echo "Calling deploy webhook..."
      #     curl -X POST -H "Content-Type: application/json" -d '{"ref":"'"${{ github.ref }}"'","sha":"'"${{ github.sha }}"'"}' "$RENDER_DEPLOY_WEBHOOK"
      #   env:
      #     RENDER_DEPLOY_WEBHOOK: ${{ secrets.RENDER_DEPLOY_WEBHOOK }}
