name: Format Check

on:
  pull_request:
    branches: ['**']
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  check:
    name: Prettier / Format Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Frontend - install
        run: npm ci
        working-directory: ./frontend

      - name: Frontend - format check (prettier)
        run: |
          if npm run format:check --if-present; then echo 'format check ok'; else npx prettier --check "frontend/**/*.{js,jsx,ts,tsx,json,css,scss,md,html}"; fi
        working-directory: .

      - name: Backend - install
        run: npm ci
        working-directory: ./backend

      - name: Backend - format check (prettier)
        run: |
          if npm run format:check --if-present; then echo 'format check ok'; else npx prettier --check "backend/**/*.{js,ts,json,md,html}"; fi
        working-directory: .
