name: Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: ['**']
  workflow_dispatch: {}

jobs:
  backend-audit:
    name: Backend - npm audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        working-directory: ./backend

      - name: Run npm audit (fail on high)
        run: npm audit --audit-level=high
        working-directory: ./backend

  frontend-audit:
    name: Frontend - npm audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        working-directory: ./frontend

      - name: Run npm audit (fail on high)
        run: npm audit --audit-level=high
        working-directory: ./frontend
